# Generated by Django 4.2.1 on 2023-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='form_text',
            field=models.CharField(default='question', max_length=200),
        ),
    ]
